site_name: CiWiki
theme:
  name: material
nav:
  - Головна: docs/index.md
  - Концепти: docs/concepts/index.md
  - Казкар: docs/kazkar/index.md
  - Ігрові легенди: docs/kazkar/legends/index.md
  - Плейбуки: docs/playbooks/index.md
  - Дослідження: docs/research/index.md
  - Nastrij: docs/nastrij/index.md
  - Malya: docs/malya/index.md
  - Podija: docs/podija/index.md
