site_name: CiWiki
theme:
  name: material

nav:
  - Головна: index.md
  - Концепти: concepts/index.md
  - Казкар:
      - Огляд: kazkar/index.md
      - Легенди: kazkar/legends/index.md
  - Playbooks: playbooks/index.md
  - Research: research/index.md
  - Події: podija/index.md
  - Ci: ci/index.md
