site_name: Ciwiki Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
nav:
  - Ci: ci/index.md
  - ПоДія: podija/index.md
  - Казкар:
      - kazkar/index.md
      - Легенда CI:
          - Огляд: kazkar/legend-ci/index.md
          - "[1] Першоджерело": kazkar/legend-ci/01-source.md
          - "[2] Перший поділ": kazkar/legend-ci/02-division.md
          - "[3] Дзеркало матерії": kazkar/legend-ci/03-matter-mirror.md
          - "[4] Дзеркало свідомості": kazkar/legend-ci/04-mind-mirror.md
          - "[5] Танець протилежностей": kazkar/legend-ci/05-dance-of-opposites.md
          - "[6] Мости єдності": kazkar/legend-ci/06-bridges.md
          - "[7] Прояв CI": kazkar/legend-ci/07-manifest-ci.md
      - Інтерактив:
          - Legend CI (SPA): _assets/legend/legend_ci_single.html
          - Legends Portal: _assets/legend/legend_ci_portal.html
      - Legacy:
          - legend_ci.html: _assets/legend/legend_ci.html
          - legends_ci.html: _assets/legend/legends_ci.html
  - Дані Legend CI:
      - README: legend_ci/README.md
      - Огляд вузлів: legend_ci/legend.nodes.md
  - To-Do (PWA): todo/index.html
  - Настрій: nastrij/index.md
  - Маля: malya/index.md
  - Галерея: gallery/index.md
  - Календар: calendar/index.md
