site_name: Cimeika Knowledge
site_url: https://www.cimeika.com.ua/
nav:
  - Home: index.md
  - CiWiki: ciwiki.md
  - Concepts:
      - Overview: concepts/index.md
  - Research:
      - Overview: research/index.md
  - Playbooks:
      - Overview: playbooks/index.md
  - PoDija:
      - Overview: podija/index.md
  - Malya:
      - Overview: malya/index.md
  - Nastrij:
      - Overview: nastrij/index.md
  - Ci:
      - Overview: ci/index.md
theme:
  name: material
  logo: media/logo/ci_logo.svg
  favicon: media/logo/favicon.png
