site_name: CiWiki
theme:
  name: material

nav:
  - Головна: index.md
  - Концепти:
      - Огляд: concepts/index.md
  - Казкар:
      - Огляд: kazkar/index.md
  - Плейбуки:
      - Огляд: playbooks/index.md
  - Дослідження:
      - Огляд: research/index.md
