site_name: ciwiki
theme:
  name: material
  logo: assets/logo.svg
plugins:
  - search
  - minify
markdown_extensions:
  - admonition
  - toc
strict: true

nav:
  - Ci: ci/index.md
  - Казкар:
      - Легенда CI: kazkar/legend.md
  - ПоДія: podiya/index.md
  - Настрій: nastrij/index.md
  - Маля: malya/index.md
  - Галерея: gallery/index.md
  - Календар: calendar/index.md
  - Концепти:
      - Константи: concepts/constants.md
extra_css:
  - assets/extra.css
